apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-hello
  name: nodejs-hello
  namespace: vault-demo
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: nodejs-hello
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-hello
  name: nodejs-hello
  namespace: vault-demo
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-hello
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodejs-hello
    spec:
      containers:
        - env: []
          envFrom:
            - configMapRef:
                name: app-env
          image: dmakeroam/nodejs-hello:1.0.4
          imagePullPolicy: Always
          name: nodejs-hello
          ports:
            - containerPort: 3000
              name: nodejs-hello
          volumeMounts: []
      serviceAccountName: nodejs-hello
      volumes: []
